export const VIDEOSLOCALINFO = [
  {
    "filename": "LOCAL_BAND_Zorn_Michief_Devils_Night_outdoor_local_10_30_2017_ewyG1lIOQOA",
    "band": "Zorn - Mischief / Devil’s Night",
    "bandcamp": "https://zornphilly.bandcamp.com/music",
    "social": "https://www.instagram.com/zorn_philly/",
    "videographer": "@dstarfreestar",
    "videographerLink": "https://www.youtube.com/watch?v=ewyG1lIOQOA",
  },
  {
    "filename": "LOCAL_BAND_DEVIL MASTER - Acid Black Mass (Official Music Video) i-pqnibwdKw",
    "band": "Devil Master - Acid Black Mass",
    "bandcamp": "https://devilmaster.bandcamp.com/music",
    "social": "https://www.facebook.com/devilisyourmaster",
    "videographer": "@Erica Frevel",
    "videographerLink": "https://www.youtube.com/watch?v=i-pqnibwdKw",
  },
  {
    "filename": "LOCAL_BAND_Skullovich (St. Thrashricks Festival, Metro Gallery, Baltimore, Maryland, March 9th, 2024) [prRMf48IqO0]",
    "band": "Skullovich",
    "bandcamp": "https://skullovich.bandcamp.com/music",
    "social": "https://www.instagram.com/skullovich_official/",
    "videographer": "@The Renaissance Blann",
    "videographerLink": "https://www.youtube.com/watch?v=prRMf48IqO0",
  },
  {
    "filename": "LOCAL_BAND_Timesup [McGe6Z5WFgg]",
    "band": "OK Buddy - Timesup",
    "bandcamp": "https://okbuddy.bandcamp.com/",
    "social": "https://www.instagram.com/okbuddy.pa/",
  },
  {
    "filename": "LOCAL_BAND_Witching - Eschaton (Official Music Video) [20noD3q9mZg]",
    "band": "Witching - Eschaton",
    "bandcamp": "https://witching.bandcamp.com/music",
    "social": "https://www.instagram.com/witching_philly/",
  },
  {
    "filename": "LOCAL_BAND_Mannequin Pussy - ＂I Got Heaven＂ [EvgYIXc4JDA]",
    "band": "Mannequin Pussy - I Got Heaven",
    "bandcamp": "https://mannequinpussy.bandcamp.com/music",
    "social": "https://www.instagram.com/mannequinpussy/",
  },
  {
    "filename": "LOCAL_BAND_NECROSEXUAL ＂DEAD SEXY＂ Music Video [OHV4Cz0NRuk]",
    "band": "Necro Sexual - Dead Sexy",
    "bandcamp": "https://necrosexual.bandcamp.com/music",
    "social": "https://www.instagram.com/thenecrosexual/",
  },
  {
    "filename": "LOCAL_BAND_SPITER ＂Tortured Soul＂ [3Ej32k_F5Hk]",
    "band": "Spiter - Tortured Soul",
    "bandcamp": "https://spiter.bandcamp.com/music",
    "social": "https://www.instagram.com/spiter666/",
  },
  {
    "filename": "LOCAL_BAND_Doused - Hybrid Moments [fr7TBfCNccM]",
    "band": "Doused - Hybrid Moments",
    "bandcamp": "https://dousedphl.bandcamp.com/music",
    "social": "https://www.instagram.com/dousedphl",
  },
  {
    "filename": "LOCAL_BAND_MORGUL BLADE - Heavy Metal Wraiths (OFFICIAL VIDEO) [MCnhn4kbst8]",
    "band": "Morgul Blade - Heavy Metal Wraiths",
    "bandcamp": "https://morgulblade.bandcamp.com/music",
    "social": "https://www.instagram.com/morgul_blade_hm/",
  },
  {
    "filename": "LOCAL_BAND_Knuckle Deep - Gaslight LIVE! At The Crawlspace (9.18.21) [lW39elk-NcQ]",
    "band": "Knuckle Deep - Gaslight",
    "bandcamp": "https://knuckledeep.bandcamp.com/music",
    "social": "https://www.instagram.com/knuckledeeptv/",
  },
  {
    "filename": "LOCAL_FILM_PIZZA PARTY MASSACRE - Official Trailer [93QAvv8mzJ4]",
    "film": "Pizza Party Massacre (2024)",
    "mainLink": "https://www.sickslicestudios.com/",
    "social": "https://www.instagram.com/luthersmidfrightsnack/",
  },
  {
    "filename": "LOCAL_FILM_HeBGB TV OFFICIAL TRAILER [xcYsf_g8ju8]",
    "film": "HeBGB TV (2022)",
    "mainLink": "https://www.hebgbtv.com/",
    "social": "https://www.instagram.com/birthdayjake/",
  },
  {
    "filename": "LOCAL_FILM_A Corpse For Christmas - Nice Trailer (blurred) - by Brewce Longo, starring Kasper Meltedhair [4LQETGyt5b4]",
    "film": "A Corpse for Christmas (2023)",
    "mainLink": "https://bloodsickproductions.bigcartel.com/",
    "social": "https://www.instagram.com/bloodsickproductions/",
  },
  {
    "filename": "LOCAL_FILM_Coven of the Black Cube - 2024 Trailer - from Blood Sick Productions [8PvuhB5ii9g]",
    "film": "Coven of the Black Cube (2024)",
    "mainLink": "https://bloodsickproductions.bigcartel.com/",
    "social": "https://www.instagram.com/bloodsickproductions/",
  },  
  {
    "filename": "LOCAL_FILM_CADDY HACK  - OFFICIAL TRAILER [r5ekIlimxxw]",
    "film": "Caddy Hack (2023)",
    "mainLink": "https://www.wildeyereleasing.com/",
    "social": "https://www.instagram.com/wildeyemovies/",
  },  
]